### ISSUE TITLE
Cannot run program "magick"

### ISSUE THREAD

**Issue by Shashank02051997** [jcraane/kmm-images#13]
I am getting the below error while creating the build

Cannot run program "magick" (in directory "."): error=2, No such file or directory

I have updated the android studio to the stable version after that update this error started showing on my build console.
```
Android Studio Bumblebee | 2021.1.1
Build #AI-211.7628.21.2111.8092744, built on January 19, 2022
Runtime version: 11.0.11+0-b60-7590822 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
```

Any idea how i can resolve it?

**Comment by jcraane** [comment]
Thanks for reporting. I cannot reproduce the issue yet (with Bumblebee on M1). 

Do you get this error when running the Android application from the run menu in Android Studio?

**Comment by Shashank02051997** [comment]
@jcraane Yes while creating the build i am getting this error

**Comment by jcraane** [comment]
Could you verify what the build output is when you execute the build from the command line? By executing ` ./gradlew build ` in the root of the project.

**Comment by Shashank02051997** [comment]
[build_error.txt](https://github.com/jcraane/kmm-images/files/7959925/build_error.txt)
Please check this file

**Comment by jcraane** [comment]
I see indeed the gradle build works whereas the Android Studio one does not.

I think it could be related to [](https://twitter.com/softwarejameson/status/1486192383716909057) (Bumblebee not sourcing in environment variables, hence the path to magick cannot be found)

This is an older thread with some example of how to launch Android Studio (as a temporary fix) from the command line: [](https://github.com/react-native-community/cli/issues/644)
