### ISSUE TITLE
image magick not located in usr/local/bin on M1 Mac

### ISSUE THREAD

**Issue by burnhamd** [jcraane/kmm-images#6]
On apple silicon brew not installs all native binaries to the /opt/homebrew/bin location instead.

This breaks compatibility with this library.  Suggested solution would be to drop the path altogether so that it uses whatever is in the path.

**Comment by jcraane** [comment]
Thanks for report and good point. I am going to drop the path when executing the magick tool. You can expect a new version in the next couple of days.

**Comment by jcraane** [comment]
I published a new version alpha07 (https://plugins.gradle.org/plugin/dev.jamiecraane.plugins.kmmimages) which has the path dropped.
